/**********************************************************************
 * Extern for targaryen
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var targaryen = {
  "setFirebaseData": function () {},
  "setFirebaseRules": function () {},
  "setDebug": function () {},
  "users": {
    "unauthenticated": {},
    "facebook": {
      "uid": {},
      "id": {},
      "provider": {}
    },
    "twitter": {
      "uid": {},
      "id": {},
      "provider": {}
    },
    "github": {
      "uid": {},
      "id": {},
      "provider": {}
    },
    "google": {
      "uid": {},
      "id": {},
      "provider": {}
    },
    "anonymous": {
      "uid": {},
      "id": {},
      "provider": {}
    },
    "password": {
      "uid": {},
      "id": {},
      "provider": {}
    }
  },
  "utils": {
    "userDefinitions": {
      "unauthenticated": {},
      "facebook": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "twitter": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "github": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "google": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "anonymous": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "password": {
        "uid": {},
        "id": {},
        "provider": {}
      }
    },
    "readableError": function () {},
    "unreadableError": function () {},
    "writableError": function () {},
    "unwritableError": function () {},
    "setDebug": function () {},
    "assertConfigured": function () {},
    "setFirebaseData": function () {},
    "getFirebaseData": function () {},
    "setFirebaseRules": function () {},
    "getFirebaseRules": function () {},
    "makeNewStore": function () {
      return {
        "get": function(){},
        "set": function(){},
        "remove": function(){},
        "snapshot": function(){
           return {
             "get": function(){},
             "val": function(){},
             "exists": function(){},
             "child": function(){},
             "parent": function(){},
             "hasChild": function(){},
             "hasChildren": function(){},
             "isNumber": function(){},
             "isString": function(){},
             "isBoolean": function(){}
           }
        }
      }
    },
    "makeNewRuleSet": function () {
      return {
        "get": function(){},
        "tryRead": function(){},
        "tryWrite": function(){},
        "tryPatch": function(){},
      }
    }
  },
  "chai": {
    "users": {
      "unauthenticated": {},
      "facebook": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "twitter": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "github": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "google": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "anonymous": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "password": {
        "uid": {},
        "id": {},
        "provider": {}
      }
    },
    "setFirebaseData": function () {},
    "setFirebaseRules": function () {}
  },
  "jasmine": {
    "setFirebaseData": function () {},
    "setFirebaseRules": function () {},
    "users": {
      "unauthenticated": {},
      "facebook": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "twitter": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "github": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "google": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "anonymous": {
        "uid": {},
        "id": {},
        "provider": {}
      },
      "password": {
        "uid": {},
        "id": {},
        "provider": {}
      }
    },
    "matchers": {
      "canRead": function () {},
      "cannotRead": function () {},
      "canWrite": function () {},
      "cannotWrite": function () {},
      "canPatch": function () {},
      "cannotPatch": function () {}
    }
  }
};
/**********************************************************************
 * End Generated Extern for targaryen
/**********************************************************************/